# TCL File Generated by Component Editor 15.1
# Tue May 30 18:26:07 JST 2017
# DO NOT MODIFY


# 
# simple_pio_0 "simple_pio_0" v1.0
#  2017.05.30.18:26:07
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module simple_pio_0
# 
set_module_property DESCRIPTION ""
set_module_property NAME simple_pio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME simple_pio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL simple_pio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file simple_pio.v VERILOG PATH simple_pio.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point simple_pio_b
# 
add_interface b avalon end
set_interface_property b addressUnits WORDS
set_interface_property b associatedClock clock
set_interface_property b associatedReset reset
set_interface_property b bitsPerSymbol 8
set_interface_property b burstOnBurstBoundariesOnly false
set_interface_property b burstcountUnits WORDS
set_interface_property b explicitAddressSpan 0
set_interface_property b holdTime 0
set_interface_property b linewrapBursts false
set_interface_property b maximumPendingReadTransactions 0
set_interface_property b maximumPendingWriteTransactions 0
set_interface_property b readLatency 0
set_interface_property b readWaitTime 1
set_interface_property b setupTime 0
set_interface_property b timingUnits Cycles
set_interface_property b writeWaitTime 0
set_interface_property b ENABLED true
set_interface_property b EXPORT_OF ""
set_interface_property b PORT_NAME_MAP ""
set_interface_property b CMSIS_SVD_VARIABLES ""
set_interface_property b SVD_ADDRESS_GROUP ""

add_interface_port b address_b address Input 4
add_interface_port b writedata_b writedata Input 32
add_interface_port b readdata_b readdata Output 32
add_interface_port b write_b write Input 1
set_interface_assignment b embeddedsw.configuration.isFlash 0
set_interface_assignment b embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment b embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment b embeddedsw.configuration.isPrintableDevice 0


# 
# connection point simple_pio_a
# 
add_interface a avalon end
set_interface_property a addressUnits WORDS
set_interface_property a associatedClock clock
set_interface_property a associatedReset reset
set_interface_property a bitsPerSymbol 8
set_interface_property a burstOnBurstBoundariesOnly false
set_interface_property a burstcountUnits WORDS
set_interface_property a explicitAddressSpan 0
set_interface_property a holdTime 0
set_interface_property a linewrapBursts false
set_interface_property a maximumPendingReadTransactions 0
set_interface_property a maximumPendingWriteTransactions 0
set_interface_property a readLatency 0
set_interface_property a readWaitTime 1
set_interface_property a setupTime 0
set_interface_property a timingUnits Cycles
set_interface_property a writeWaitTime 0
set_interface_property a ENABLED true
set_interface_property a EXPORT_OF ""
set_interface_property a PORT_NAME_MAP ""
set_interface_property a CMSIS_SVD_VARIABLES ""
set_interface_property a SVD_ADDRESS_GROUP ""

add_interface_port a address_a address Input 4
add_interface_port a writedata_a writedata Input 32
add_interface_port a readdata_a readdata Output 32
add_interface_port a write_a write Input 1
set_interface_assignment a embeddedsw.configuration.isFlash 0
set_interface_assignment a embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment a embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment a embeddedsw.configuration.isPrintableDevice 0

